dotenv: .env
dependencies:
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
    - '@openzeppelin/=/home/daniel/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.5.0'
wallets:
  from_key: ${PRIVATE_KEY}