dotenv: .env
networks:
  kovan:
    # Address from google
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
 
    # Address from https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts
    lending_pool_addresses_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'

    # Address from https://docs.chain.link/docs/ethereum-addresses/#Kovan%20Testnet
    dai_to_eth_pricefeed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
 
    # Address from google
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
  
  mainnet-fork-dev:
    # Address from google
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    
    # Address from https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'

    # Address from https://docs.chain.link/docs/ethereum-addresses/#Ethereum%20Mainnet
    dai_to_eth_pricefeed: '0x773616E4d11A78F511299002da57A0a94577F1f4'

    # Address from google
    dai_token: '0x6B175474E89094C44Da98b954EedeAC495271d0F'

wallets:
  from_key: ${PRIVATE_KEY}